openapi: 3.1.0
info:
  title: Fiverr Gig Search API
  description: Busca gigs en Fiverr y devuelve título, precio, vendedor, rating y link de afiliado.
  version: 1.0.0
servers:
  - url: https://fiverr-api-gpt.onrender.com
paths:
  /fiverr/search:
    post:
      summary: Buscar gigs en Fiverr
      operationId: buscarGigs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: edición de video
      responses:
        "200":
          description: Lista de gigs encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titulo:
                      type: string
                      example: I will edit an engaging vlog for youtube
                    precio:
                      type: string
                      example: From $25
                    vendedor:
                      type: string
                      example: video_master21
                    rating:
                      type: string
                      example: 4.9
                    link_afiliado:
                      type: string
                      example: https://go.fiverr.com/visit/?bta=1114947&brand=fiverrmarketplace&url=https://www.fiverr.com/seller/gig-title
