services:
  - type: web
    name: fiverr-api-gpt
    env: python
    region: frankfurt
    plan: free
    buildCommand: poetry install && poetry run playwright install
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - "*"
